version: '3'
services:
  database:
    restart: always
    image: mongo:3.4-jessie
    ports:
      - 27017:27017
    volumes:
      - /data/db:/data/db
    networks:
      - bitcoin-network

  bitcoin-node:
    build: ./bitcoin-core
    restart: always
    expose:
      - 18333
      - 18332
    volumes:
      - /data-btc-testnet:/home/btc-data
    networks:
      - bitcoin-network
    environment:
      - CONFIG_FILENAME=bitcoin.conf

  bitcoin-node-mainnet:
    build: ./bitcoin-core
    restart: always
    expose:
      - 8333
      - 8332
    volumes:
      - /data-btc-mainnet:/home/btc-data
    networks:
      - bitcoin-network
    environment:
      - CONFIG_FILENAME=bitcoin.mainnet.conf

  bitcore-node:
    build: ./bitcore
    restart: always
    image: bitcore-node-image
    expose:
      - 3000
    ports:
      - 3000:3000
    links:
      - database
    networks:
      - bitcoin-network
      - nginx-network
    depends_on:
      - bitcoin-node
    environment:
      - DB_HOST=database
    env_file: .env

  insight-testnet:
    image: insight-testnet-image
    container_name: insight-testnet
    build: ./bitcore/packages/insight
    links:
      - bitcore-node
    depends_on:
      - bitcore-node
    ports:
      - 8200:8200
    links:
      - bitcore-node
    networks:
      - bitcoin-network
      - nginx-network
    environment:
      - NETWORK=testnet

  insight-nginx:
    image: nginx:latest
    container_name: insight_nginx
    links:
      - insight-testnet
    networks:
      - nginx-network
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/conf.d/:/etc/nginx/conf.d/
      - ./nginx/log/:/var/log/nginx/
      - ./nginx/cache/:/etc/nginx/cache
      - /etc/letsencrypt/:/etc/letsencrypt/
      - ./.well-known/:/var/www/html/.well-known/

networks:
        nginx-network:
        bitcoin-network:
        insight-network:
          driver: bridge
