version: '3'
services:
  database:
    restart: always
    image: mongo:3.4-jessie
    ports: 
      - 27017:27017
    volumes: 
      - /data/db:/data/db
    networks:
      - bitcoin-network
    
  bitcoin-node:
    build: ./bitcoin-core
    restart: always
    expose:
      - 18333
      - 18332
    networks:
      - bitcoin-network

  bitcore-node:
    build: ./bitcore
    restart: always
    image: bitcore-node-image
    expose:
      - 3000
    ports:
      - 3000:3000
    links:
      - database
    networks:
      - bitcoin-network
      - nginx-network
    depends_on:
      - bitcoin-node
    environment:
      - DB_HOST=database
    env_file: .env

  insight-testnet:
    image: insight-testnet-image
    container_name: insight-testnet
    build: ./bitcore/packages/insight
    links:
      - bitcore-node
    depends_on:
      - bitcore-node
    ports:
      - 8200:8200
    links:
      - bitcore-node
    networks:
      - bitcoin-network
      - nginx-network
    environment:
      - NETWORK=testnet

  insight-nginx:
    image: nginx:latest
    container_name: insight_nginx
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx/conf
      - ./nginx/error.log:/etc/nginx/error_log.log
      - ./nginx/cache/:/etc/nginx/cache
      - /etc/letsencrypt/:/etc/letsencrypt/

    #  bws:
    #    build: ./bitcore/packages/bitcore-wallet-service
    #    container_name: bws
    #    image: bws-image
    #    restart: always
    #    links:
    #      - bitcore-node
    #    ports:
    #      - 3232:3232
    #    networks:
    #      - nginx-network
    #      - bitcoin-network


networks:
        nginx-network:
        bitcoin-network:
          driver: bridge
